<?php

namespace App\Http\Controllers\Traits;

trait Tags
{

    protected $tagsMap = [];

    //not a  __constructor because those methods is not effacted by app locale
    public function constructTagsMap()
    {
        $this->tagsMap = [
            '0' => __('tags.other'),
            '1' => __('tags.bit'),
                '1.1' => __('tags.bicentric'),
                '1.2' => __('tags.bitBreaker'),
                '1.3' => __('tags.bitDevice'),
                '1.4' => __('tags.wing'),
                '1.5' => __('tags.bitNozzle'),
                '1.6' => __('tags.pneumo'),
                '1.7' => __('tags.cone'),
                '1.8' => __('tags.carbide'),
                '1.9' => __('tags.pdc'),
                '1.10' => __('tags.tsp'),
            '2' => __('tags.dp'),
                '2.1' => __('tags.slipJoint'),
                '2.2' => __('tags.ldp'),
                '2.3' => __('tags.floatCollar'),
                '2.4' => __('tags.joint'),
                '2.5' => __('tags.xOver'),
                    '2.5.1' => __('tags.xOverDump'),
                '2.6' => __('tags.packerRubber'),
                '2.7' => __('tags.stabilizersOnPipe'),
                '2.8' => __('tags.pipeStd'),
                '2.9' => __('tags.hwdp'),
                '2.10' => __('tags.dc'),
                    '2.10.1' => __('tags.dcSlick'),
                    '2.10.2' => __('tags.dcSpiral'),
                '2.11' => __('tags.filters'),
                '2.12' => __('tags.centralizers'),
                '2.13' => __('tags.drift'),
            '3' => __('tags.rig'),
                '3.1' => __('tags.mastTools'),
                '3.2' => __('tags.drillerHouse'),
                '3.3' => __('tags.mast'),
                '3.4' => __('tags.mdu'),
                '3.5' => __('tags.catWalks'),
                '3.6' => __('tags.substructure'),
                '3.7' => __('tags.monkeyBoard'),
                '3.8' => __('tags.dogHouse'),
                '3.9' => __('tags.rail'),
                '3.10' => __('tags.rigUpDown'),
            '4' => __('tags.pump'),
                '4.1' => __('tags.pumpiI'),
                '4.2' => __('tags.hydComonents'),
                    '4.2.1' => __('tags.hydActuator'),
                    '4.2.2' => __('tags.hydPulser'),
                    '4.2.3' => __('tags.hydController'),
                '4.3' => __('tags.mudPumps'),
                    '4.3.1' => __('tags.engine'),
                    '4.3.2' => __('tags.floatCollar'),
                    '4.3.3' => __('tags.pumpController'),
                    '4.3.4' => __('tags.pumpSupercharger'),
                    '4.3.5' => __('tags.pneumaticCompensator'),
                    '4.3.6' => __('tags.suctionFiler'),
                    '4.3.7' => __('tags.pressureFiler'),
                    '4.3.8' => __('tags.safeValve'),
                    '4.3.9' => __('tags.cooling'),
                    '4.3.10' => __('tags.component'),
                '4.4' => __('tags.pumpPD'),
                '4.5' => __('tags.pumpCent'),
                '4.6' => __('tags.pumpPlunger'),
                '4.7' => __('tags.pumpSinking'),
                '4.8' => __('tags.component'),
                    '4.8.1' => __('tags.compensator'),
                    '4.8.2' => __('tags.floatCollar'),
                    '4.8.3' => __('tags.filters'),
                    '4.8.4' => __('tags.barrel'),
            '5' => __('tags.mud'),
                '5.1' => __('tags.filter'),
                '5.2' => __('tags.hose'),
                '5.3' => __('tags.compressor'),
                '5.4' => __('tags.linesHP'),
                '5.5' => __('tags.manifold'),
                '5.6' => __('tags.buffer'),
                '5.7' => __('tags.clear'),
                    '5.7.1' => __('tags.shaker'),
                    '5.7.2' => __('tags.degasser'),
                    '5.7.3' => __('tags.desilter'),
                    '5.7.4' => __('tags.desender'),
                '5.8' => __('tags.prepare'),
                    '5.8.1' => __('tags.mixer'),
                    '5.8.2' => __('tags.mudCone'),
                    '5.8.3' => __('tags.mixingUnit'),
                '5.9' => __('tags.store'),
                    '5.9.1' => __('tags.mudTanks'),
                '5.10' => __('tags.recycling'),
                '5.11' => __('tags.standPipe'),
                '5.12' => __('tags.trashPump'),
            '6' => __('tags.boreholeSurvey'),
                '6.1' => __('tags.coring'),
                    '6.1.1' => __('tags.coringBox'),
                    '6.1.2' => __('tags.coreBBL'),
                    '6.1.3' => __('tags.coringReciever'),
                    '6.1.4' => __('tags.coringPipe'),
                    '6.1.5' => __('tags.coringBit'),
                '6.2' => __('tags.wellLoginng'),
                    '6.2.1' => __('tags.loggingVideo'),
                    '6.2.2' => __('tags.misc'),
                    '6.2.3' => __('tags.loggingDirectional'),
                    '6.2.4' => __('tags.caliperLog'),
                    '6.2.5' => __('tags.loggingUnit'),
                    '6.2.6' => __('tags.coil'),
                    '6.2.7' => __('tags.winch'),
                    '6.2.8' => __('tags.loggingMagnetic'),
                    '6.2.9' => __('tags.waterFlow'),
                    '6.2.10' => __('tags.radiometrics'),
                    '6.2.11' => __('tags.flowSurvey'),
                    '6.2.12' => __('tags.recordingSystem'),
                    '6.2.13' => __('tags.seismicMeasurements'),
                    '6.2.14' => __('tags.photometryNephelometry'),
                    '6.2.15' => __('tags.geoelectricSurvey'),
            '7' => __('tags.miscHelpEq'),
                '7.1' => __('tags.grinding'),
                    '7.1.1' => __('tags.grindingM'),
                    '7.1.2' => __('tags.grindingC'),
                '7.2' => __('tags.washingMachine'),
                '7.3' => __('tags.wrench'),
                '7.4' => __('tags.lineMount'),
                '7.5' => __('tags.cutter'),
                '7.6' => __('tags.welding'),
                    '7.6.1' => __('tags.gasWeld'),
                    '7.6.1' => __('tags.electroWeld'),
            '8' => __('tags.motor'),
                '8.1' => __('tags.rotational'),
                '8.2' => __('tags.percussion'),
                '8.3' => __('tags.pneumatic'),
                '8.4' => __('tags.pdm'),
                '8.5' => __('tags.electrical'),
            '9' => __('tags.parts'),
            '10' => __('tags.control'),
                '10.1' => __('tags.indicator'),
                '10.2' => __('tags.measurmentEq'),
                '10.3' => __('tags.cable'),
                '10.4' => __('tags.camera'),
                '10.5' => __('tags.registerEq'),
                '10.6' => __('tags.loggingGage'),
            '11' => __('tags.stub'),
                '11.1' => __('tags.stubB'),
                '11.2' => __('tags.stubP'),
                '11.3' => __('tags.stubE'),
                '11.4' => __('tags.stubR'),
                '11.5' => __('tags.stubCone'),
                '11.6' => __('tags.stubPD'),
            '12' => __('tags.camp'),
                '12.1' => __('tags.shower'),
                '12.2' => __('tags.house'),
                '12.3' => __('tags.kitchen'),
                '12.4' => __('tags.med'),
                '12.5' => __('tags.wc'),
                '12.6' => __('tags.electrics'),
            '13' => __('tags.casingCementing'),
                '13.1' => __('tags.shoe'),
                '13.2' => __('tags.casingPipe'),
                '13.3' => __('tags.casingEq'),
                    '13.3.1' => __('tags.box'),
                    '13.3.2' => __('tags.floatCollar'),
                    '13.3.3' => __('tags.guidePlug'),
                    '13.3.4' => __('tags.centraliserTurbulizer'),
                '13.4' => __('tags.joint'),
                '13.5' => __('tags.xOver'),
                '13.6' => __('tags.scratcher'),
                '13.7' => __('tags.cementing'),
                    '13.7.1' => __('tags.cementingBasket'),
                    '13.7.2' => __('tags.DVCollar'),
                    '13.7.3' => __('tags.stingerCementing'),
                    '13.7.4' => __('tags.cementBridge'),
                    '13.7.5' => __('tags.floatCollar'),
                    '13.7.6' => __('tags.packer'),
                    '13.7.7' => __('tags.cementPlugs'),
                    '13.7.8' => __('tags.cementBaffleCollar'),
            '14' => __('tags.emergency'),
                '14.1' => __('tags.emergencyValve'),
                '14.2' => __('tags.bath'),
                '14.3' => __('tags.fishingTool'),
                    '14.3.1' => __('tags.overShot'),
                    '14.3.2' => __('tags.magnetic'),
                    '14.3.3' => __('tags.taperTap'),
                '14.4' => __('tags.sigil'),
                '14.5' => __('tags.mill'),
                '14.6' => __('tags.junkBasket'),
            '15' => __('tags.lubricator'),
                '15.1' => __('tags.lubricatorDP'),
                '15.2' => __('tags.lubricatorTong'),
                '15.3' => __('tags.lubricatorPump'),
                '15.4' => __('tags.lubricatorTubing'),
                '15.5' => __('tags.lubricatorCasing'),
            '16' => __('tags.tubingEq'),
                '16.1' => __('tags.knockOffValve'),
                '16.2' => __('tags.collTubing'),
                '16.3' => __('tags.tubing'),
                '16.4' => __('tags.joint'),
                '16.5' => __('tags.xOver'),
            '17' => __('tags.wellHeadEq'),
                '17.1' => __('tags.casingSpool'),
                '17.2' => __('tags.xMassTree'),
            '18' => __('tags.packer'),
                '18.1' => __('tags.packerPumps'),
                '18.2' => __('tags.floatCollar'),
                '18.3' => __('tags.packerStd'),
                '18.4' => __('tags.packerPipes'),
                '18.5' => __('tags.packerHoses'),
            '19' => __('tags.airUtility'),
                '19.1' => __('tags.airLine'),
                '19.2' => __('tags.airTank'),
                '19.3' => __('tags.compensator'),
                '19.4' => __('tags.airDrier'),
            '20' => __('tags.boe'),
                '20.1' => __('tags.controlUnit'),
                    '20.1.1' => __('tags.hydro'),
                    '20.1.2' => __('tags.manual'),
                    '20.1.3' => __('tags.remote'),
                '20.2' => __('tags.degasser'),
                '20.3' => __('tags.bopValveWheel'),
                '20.4' => __('tags.line'),
                    '20.4.1' => __('tags.kill'),
                    '20.4.2' => __('tags.chock'),
                '20.5' => __('tags.manifold'),
                    '20.5.1' => __('tags.kill'),
                    '20.5.2' => __('tags.chock'),
                '20.6' => __('tags.ram'),
                    '20.6.1' => __('tags.blind'),
                    '20.6.2' => __('tags.cut'),
                    '20.6.3' => __('tags.pipe'),
                '20.7' => __('tags.bop'),
                    '20.7.1' => __('tags.singleBop'),
                    '20.7.2' => __('tags.doubleBop'),
                    '20.7.3' => __('tags.annular'),
                    '20.7.4' => __('tags.drillingSpool'),
                '20.8' => __('tags.flare'),
                    '20.8.1' => __('tags.flareBody'),
                    '20.8.2' => __('tags.flareControl'),
                    '20.8.3' => __('tags.flareActivator'),
                    '20.8.4' => __('tags.flareLines'),
            '21' => __('tags.rotory'),
                '21.1' => __('tags.kelly'),
                '21.2' => __('tags.swivel'),
                '21.3' => __('tags.tdsSystem'),
                    '21.3.1' => __('tags.emergencySys'),
                    '21.3.2' => __('tags.shaft'),
                    '21.3.3' => __('tags.hydraulicSys'),
                    '21.3.4' => __('tags.mudPipe'),
                    '21.3.5' => __('tags.sensor'),
                    '21.3.6' => __('tags.controllStantion'),
                    '21.3.7' => __('tags.component'),
                    '21.3.8' => __('tags.ballValve'),
                    '21.3.9' => __('tags.tdsRail'),
                    '21.3.10' => __('tags.floatCollar'),
                    '21.3.11' => __('tags.washPipe'),
                    '21.3.12' => __('tags.ControllUnit'),
                    '21.3.13' => __('tags.bail'),
                    '21.3.14' => __('tags.electroEngines'),
                '21.4' => __('tags.rotor'),
                    '21.4.1' => __('tags.kellyBush'),
                    '21.4.2' => __('tags.component'),
                    '21.4.3' => __('tags.rotorDrive'),
                    '21.4.4' => __('tags.brakes'),
            '22' => __('tags.power'),
                '22.1' => __('tags.distributionUnit'),
                '22.2' => __('tags.generator'),
                '22.3' => __('tags.cabel'),
                '22.4' => __('tags.transformator'),
            '23' => __('tags.simCasing'),
                '23.1' => __('tags.simCasingS'),
                '23.2' => __('tags.simCasingB'),
                    '23.2.1' => __('tags.simCasingBS'),
                    '23.2.2' => __('tags.simCasingBB'),
            '24' => __('tags.diselStorage'),
                '24.1' => __('tags.bomb'),
                '24.2' => __('tags.fillingStation'),
                '24.3' => __('tags.tanks'),
                '24.4' => __('tags.measuringEq'),
                '24.5' => __('tags.fuel'),
            '25' => __('tags.specMachinery'),
                '25.1' => __('tags.crane'),
                '25.2' => __('tags.forklifter'),
                '25.3' => __('tags.truck'),
                '25.4' => __('tags.cementingTruck'),
            '26' => __('tags.lifting'),
                '26.1' => __('tags.emergencyDrive'),
                '26.2' => __('tags.drillHook'),
                '26.3' => __('tags.drillLineSys'),
                    '26.3.1' => __('tags.reel'),
                    '26.3.2' => __('tags.drive'),
                    '26.3.3' => __('tags.cooling'),
                    '26.3.4' => __('tags.brakes'),
                    '26.3.5' => __('tags.drillLine'),
                    '26.3.6' => __('tags.electroEngines'),
                '26.4' => __('tags.handlingWinch'),
                '26.5' => __('tags.deadAnchor'),
                '26.6' => __('tags.crownBlock'),
                '26.7' => __('tags.travelBlock'),
            '27' => __('tags.pipeHandling'),
                '27.1' => __('tags.heavingPlug'),
                '27.2' => __('tags.manualClamp'),
                '27.3' => __('tags.pipeClamp'),
                '27.4' => __('tags.casingGrip'),
                '27.5' => __('tags.elevator'),
                    '27.5.1' => __('tags.elevatorS'),
                    '27.5.2' => __('tags.elevatorI'),
            '28' => __('tags.hseEq'),
                '28.1' => __('tags.fireHazard'),
                '28.2' => __('tags.signalization'),
                '28.3' => __('tags.lifeSupport'),
                '28.4' => __('tags.light'),
                '28.5' => __('tags.ppo'),
                '28.6' => __('tags.misc'),
            '29' => __('tags.tong'),
                '29.1' => __('tags.component'),
                '29.2' => __('tags.tongHy'),
                    '29.2.1' => __('tags.tongHyControll'),
                '29.3' => __('tags.tongTubing'),
                '29.4' => __('tags.tongCasing'),
                '29.5' => __('tags.tongManual'),
                '29.6' => __('tags.tongF'),
                '29.7' => __('tags.tongP'),
                '29.8' => __('tags.tongC'),
                '29.9' => __('tags.tongHi'),
            '30' => __('tags.pipeLocking'),
                '30.1' => __('tags.slip'),
                '30.2' => __('tags.spider'),
            '31' => __('tags.chemics'),
                '31.1' => __('tags.sequesteringAgentFiltrationControl'),
                '31.2' => __('tags.mudHeaver'),
                '31.3' => __('tags.LCM'),
                '31.4' => __('tags.bentoniteAlternate'),
                '31.5' => __('tags.nonOrganic'),
                '31.6' => __('tags.lubticants'),
            '32' => __('tags.chemLab'),
                '32.1' => __('tags.densityEq'),
                '32.2' => __('tags.asgEq'),
                '32.3' => __('tags.viscosityEq'),
                '32.4' => __('tags.sssEq'),
                '32.5' => __('tags.pHEq'),
                '32.6' => __('tags.waterLossEq'),
            '33' => __('tags.jar'),
                '33.1' => __('tags.hyrdoMeck'),
                '33.2' => __('tags.hydraulic'),


            // SERVESES
            '50' => __('tags.otherService'),
            '51' => __('tags.multipleService'),
            '52' => __('tags.emergencySe'),
            '53' => __('tags.controll'),
            '54' => __('tags.airWaste'),
            '55' => __('tags.loggingSe'),
                '55.1' => __('tags.coringSe'),
                '55.2' => __('tags.stdWellLog'),
            '56' => __('tags.ndt'),
            '57' => __('tags.bitSe'),
            '58' => __('tags.dhmSe'),
            '59' => __('tags.grounding'),
            '60' => __('tags.sideHole'),
            '61' => __('tags.directionalDrilling'),
            '62' => __('tags.casingSe'),
            '63' => __('tags.guard'),
            '64' => __('tags.bopSe'),
            '65' => __('tags.training'),
            '66' => __('tags.pipeShipment'),
            '67' => __('tags.sellControllFuel'),
            '68' => __('tags.vihacle'),
            '69' => __('tags.builders'),
            '70' => __('tags.loggingSt'),
            '71' => __('tags.transport'),
            '72' => __('tags.recyclingSe'),
                '72.1' => __('tags.recyclingDrill'),
                '72.2' => __('tags.recyclingDomestic'),
            '73' => __('tags.lab'),
            '74' => __('tags.cementingSe'),
        ];
    }

    // get the type of tag (equipment or service)
    public function getTagType($tag) {
        $dot = strpos($tag, '.');
        if ($dot) {
            $tag = substr($tag, 0, $dot);
        }
        if ( $tag < '50' ) {
            return 'eq';
        } else {
            return 'se';
        }
    }

    // transform '2.3.1.4' to 'drillingEq, drillString, upGround, slip'
    public function getTagReadable($id) {
        $this->constructTagsMap();
        $tagsMap = $this->getTagMap($id);
        $tagsInString = '';
        foreach($tagsMap as $tag) {
            $tagsInString = $tagsInString == '' ? $tag : $tagsInString.", ".$tag;
        }
        return $tagsInString;
    }

    // transform '2.3.1.4' to [2=>'drillingEq', 3=>'drillString', 1=>'upGround', 4=>'slip']
    public function getTagMap($id) {
        $this->constructTagsMap();
        $idPath = [];
        $this->getTagMapHelper($id, $idPath);
        return array_reverse($idPath, true);
    }

    // transform '2.3' to 'drillString'
    private function getTagNameById($id) {
        return $this->tagsMap[$id];
    }

    // recursive helper for getTagMap()
    private function getTagMapHelper($id, &$idPath) {
        $idPath[$id] = $this->getTagNameById($id);
        if ( strpos($id, '.') !== false ) {
            for ( $i=strlen($id)-1; $i>0 ; $i--) {
                if ($id[$i] == '.') {
                    $id = substr_replace($id ,"",-1);
                    break;
                } else {
                    $id = substr_replace($id ,"",-1);
                }
            }
            $this->getTagMapHelper($id, $idPath);
        } else {
            return;
        }
    }

    //check is value is exists
    public function tagExist ($value) {
        $this->constructTagsMap();
        return array_key_exists($value, $this->tagsMap);
    }

}
